/*
 * This source file was generated by the Gradle 'init' task
 */
package de.lschnartzke.fscramble

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
    }
}
